
ifndef	BASEDIR
BASEDIR		:=$(shell pwd)/..
endif
include $(BASEDIR)/Rules.mk

#------------------------------------------------------------------------------

SUBDIRS		:= watchdog \
			   config \
			   action

#------------------------------------------------------------------------------

include $(BASEDIR)/build/Rules.common
