
ifndef	BASEDIR
BASEDIR		:=$(shell pwd)/..
endif
include $(BASEDIR)/Rules.mk

#------------------------------------------------------------------------------

SUBDIRS		:= watchdog \
			   config

#------------------------------------------------------------------------------

include $(BASEDIR)/build/Rules.common
