
ifndef	BASEDIR
BASEDIR		:=$(shell pwd)/..
endif
include $(BASEDIR)/Rules.mk

#------------------------------------------------------------------------------

#SUBDIRS	:= helloc hellocpp vmq_test vmshm_test
SUBDIRS		:= vmqctl vmshmctl cli

#------------------------------------------------------------------------------

include $(BASEDIR)/build/Rules.common
