
ifndef	BASEDIR
BASEDIR		:=$(shell pwd)/..
endif
include $(BASEDIR)/Rules.mk

#------------------------------------------------------------------------------

SUBDIRS		:= vmqctl vmshmctl vmq_test vmshm_test

#------------------------------------------------------------------------------

include $(BASEDIR)/build/Rules.common
