#!/bin/sh

PFCMD="$1"
BASEDIR=/system
BINDIR=$BASEDIR/bin
LIBDIR=$BASEDIR/lib
DRVDIR=$BASEDIR/driver
SCRDIR=$BASEDIR/scripts
DEFDIR=$BASEDIR/default
SUDO=

fEcho() {
	echo -e "!! $1"
}

fLoadDriver() {
	_RV=`lsmod | grep vmq`
	if [ x"$_RV" == x"" ] ; then
		$SUDO $SCRDIR/pi-frame.init
	fi
	[ -n "$SUDO" ] && $SUDO chmod 0666 /dev/vmq /dev/vmshm
}

fRunService() {
	fEcho "[START] $1"
	$* &
}

fStartService() {
	fEcho "Start SERVICE !!\n"
	fRunService svc.config
}

fStopService() {
	fEcho "Stop SERVICE !!\n"
}

fInit() {
	fEcho "INIT"
	. $SCRDIR/pf-env
	if [[ $EUID -ne 0 ]]; then
		SUDO=sudo
	fi
}

fStart() {
	fEcho "START BEGIN"
	fLoadDriver
	fStartService
	fEcho "START END"
}

fStop() {
	fEcho "STOP BEGIN"
	fStopService
	fEcho "STOP END"
}

###################################################
# Main

fInit

case "$PFCMD" in
	start)
		fStart
	;;  
	stop)
		fStop
	;;
	*)  
	echo "Usage: $0 {start|stop}"
	exit 1
	;;  
esac
