#
#------------------------------------------------------------------------------

ifndef  BASEDIR
BASEDIR			:=$(shell pwd)/../..
endif
include $(BASEDIR)/Rules.mk

#------------------------------------------------------------------------------

TARGET			:=vmshmctl
OBJS			:=vmshmctl.o
INSTALLDIR		:=$(TARGETDIR)/system/bin

#------------------------------------------------------------------------------

include $(BASEDIR)/build/Rules.common
