
#ifndef	__PF_LIMIT_H__
#define	__PF_LIMIT_H__

#define	MAX_USER_COUNT					16
#define	MAX_NTP_SERVER_COUNT			8
#define	MAX_SESSION_COUNT				16
#define	MAX_EMAIL_COUNT					8
#define	MAX_LOG_COUNT					1000
#define MAX_FILE_LIST_COUNT				(2048)
#define MAX_ATA_PART_COUNT				4

#define MAX_DUMMY_LENGTH				16
#define	MAX_VERSION_LENGTH				32
#define	MAX_USERID_LENGTH				32
#define	MAX_PASSWD_LENGTH				32
#define	MAX_GROUPID_LENGTH				32
#define	MAX_HASH_LENGTH					64
#define	MAX_NAME_LENGTH					64
#define	MAX_NAME32_LENGTH				32
#define	MAX_NAME16_LENGTH				16
#define MAX_NAME8_LENGTH				8
#define	MAX_TIMEZONE_LENGTH				MAX_NAME_LENGTH
#define	MAX_ADDR_LENGTH					MAX_NAME_LENGTH
#define	MAX_PROTOCOL_LENGTH				MAX_NAME_LENGTH
#define	MAX_TITLE_LENGTH				MAX_NAME_LENGTH
#define	MAX_DEVICE_LENGTH				128
#define	MAX_UUID_LENGTH					64
#define MAX_BASE_PATH_LENGTH			128
#define	MAX_PATH_LENGTH					256
#define MAX_EDID_LENGTH					1024
#define MAX_MESSAGE_LENGTH				128
#define MAX_PARAM_LENGTH				512
#define MAX_KMSG_LENGTH					512
#define MAX_FILE_BUFFER_SIZE			(8*1024)


#endif	/*__PF_LIMIT_H__*/
